#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://www.youjiniot.com/eureka/
#server:
#  port: 8763
#spring:
#  application:
#    name: service-hi
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      percentage: 1.0
#  cloud:
#    config:
#      label: master   #指明远程仓库的分支
#      profile: dev    #开发环境配置文件
#      discovery:
#        enabled: true
#        service-id: config-server
#      name: hfz_test
#      uri: http://39.108.158.254:8888


#management:
#  security:
#    enabled: false


#http请求地址和资源文件映射如下:

 #/{application}/{profile}[/{label}]
 #/{application}-{profile}.yml
 # /{label}/{application}-{profile}.yml
 #/{application}-{profile}.properties
 #/{label}/{application}-{profile}.properties