spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ZhongWanYuXi/hfz-config
          search-paths: release
          username: ZhongWanYuXi
          password: 940707you
      label: master
  rabbitmq:
    host: 120.79.138.57
    port: 5672
    username: admin
    password: 940707you

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://www.youjiniot.com/eureka/
  instance:
    ip-address: 39.108.158.254
    prefer-ip-address: true

management:
  security:
    enabled: false

