server:
  port: 8000
spring:
  application:
    name: admin-server
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: default
        location: service-turbine
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    ip-address: 120.79.138.57
    prefer-ip-address: true
    metadata-map:
      user.name: admin
      user.password: 123456
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://hfz:youjin666@www.youjiniot.com/eureka/
#management:
#  security:
#    enabled: false

security.basic.enabled: false
security:
  user:
    name: admin
    password: 123456
#

endpoints:
  health:
    sensitive: false
    enabled: true
  actuator:
    enabled: true
    sensitive: false
  beans:
    sensitive: false
    enabled: true

info:
  version: @project.version@

logging:
  file: "logs/boot-admin-sample.log"