server:
  port: 8000
spring:
  application:
    name: admin-server
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    ip-address: 120.79.138.57
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://hfz:youjin666@www.youjiniot.com/eureka/
management:
  security:
    enabled: false

info:
  version: @project.version@

