server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  #表示是一个server
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/