server:
  port: 8761

spring:
  application:
    name: comaberenices


eureka:
  instance:
    hostname: www.youjiniot.com
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
security:
  basic:
    enabled: true
  user:
    name: hfz
    password: youjin666


#   cloud:
#       config:
#         uri: http://config:8888
#         fail-fast: true
#         password: 940707you
#         username: root