eureka:
  client:
    serviceUrl:
      defaultZone: http://hfz:youjin666@www.youjiniot.com/eureka/
  instance:
    ip-address: 120.79.138.57
    prefer-ip-address: true
server:
  port: 9411
spring:
  application:
    name: zipkin-server